import type { BrandState } from "./types";
import { buildScale, DEFAULT_STEPS, ROLE_FOR_STEP } from "./typescale";
import { ramp } from "./colour";

/**
 * Token generation.
 *
 * The point of exporting tokens rather than a PDF of swatches is that the
 * institution's engineers can consume the decisions directly, which is the only
 * mechanism that reliably keeps a large estate consistent.
 */

const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") || "colour";

export function cssTokens(state: BrandState): string {
  const scale = buildScale(state.typeBase, state.typeRatio, DEFAULT_STEPS);
  const lines: string[] = [
    `/* ${state.institution.name || "Institution"} — design tokens */`,
    `/* Generated by Waterline. Colour ramps are derived from each role's seed. */`,
    "",
    ":root {",
    "  /* Colour roles */",
  ];

  for (const c of state.palette) {
    lines.push(`  --colour-${slug(c.name)}: ${c.hex}; /* ${c.usage} */`);
  }

  lines.push("", "  /* Tonal ramps */");
  for (const c of state.palette) {
    for (const step of ramp(c.hex)) {
      lines.push(`  --colour-${slug(c.name)}-${step.step}: ${step.hex};`);
    }
  }

  lines.push("", "  /* Type */");
  lines.push(`  --font-heading: ${state.headingFamily};`);
  lines.push(`  --font-body: ${state.bodyFamily};`);
  lines.push(`  --type-base: ${state.typeBase}px;`);
  lines.push(`  --type-ratio: ${state.typeRatio};`);
  lines.push("");

  for (const s of scale) {
    const name = s.step >= 0 ? `up-${s.step}` : `down-${Math.abs(s.step)}`;
    lines.push(`  --size-${name}: ${s.rem}rem; /* ${ROLE_FOR_STEP[s.step]} */`);
    lines.push(`  --leading-${name}: ${s.lineHeight};`);
    lines.push(`  --tracking-${name}: ${s.tracking}em;`);
  }

  lines.push("}");
  return lines.join("\n");
}

export function jsonTokens(state: BrandState): string {
  const scale = buildScale(state.typeBase, state.typeRatio, DEFAULT_STEPS);
  return JSON.stringify(
    {
      $schema: "https://design-tokens.org/schema.json",
      institution: state.institution.name || "Institution",
      generated: new Date().toISOString().slice(0, 10),
      colour: Object.fromEntries(
        state.palette.map((c) => [
          slug(c.name),
          {
            $value: c.hex,
            $type: "color",
            $description: c.usage,
            scale: Object.fromEntries(ramp(c.hex).map((s) => [s.step, s.hex])),
          },
        ]),
      ),
      typography: {
        families: { heading: state.headingFamily, body: state.bodyFamily },
        base: `${state.typeBase}px`,
        ratio: state.typeRatio,
        scale: Object.fromEntries(
          scale.map((s) => [
            s.step >= 0 ? `up-${s.step}` : `down-${Math.abs(s.step)}`,
            {
              size: `${s.rem}rem`,
              lineHeight: s.lineHeight,
              tracking: `${s.tracking}em`,
              role: ROLE_FOR_STEP[s.step],
            },
          ]),
        ),
      },
    },
    null,
    2,
  );
}

export function tailwindTokens(state: BrandState): string {
  const scale = buildScale(state.typeBase, state.typeRatio, DEFAULT_STEPS);
  const lines = [
    `/* ${state.institution.name || "Institution"} — Tailwind v4 theme */`,
    `@theme {`,
  ];
  for (const c of state.palette) {
    lines.push(`  --color-${slug(c.name)}: ${c.hex};`);
    for (const s of ramp(c.hex)) {
      lines.push(`  --color-${slug(c.name)}-${s.step}: ${s.hex};`);
    }
  }
  lines.push(`  --font-heading: ${state.headingFamily};`);
  lines.push(`  --font-body: ${state.bodyFamily};`);
  for (const s of scale) {
    const name = s.step >= 0 ? `up-${s.step}` : `down-${Math.abs(s.step)}`;
    lines.push(`  --text-${name}: ${s.rem}rem;`);
    lines.push(`  --text-${name}--line-height: ${s.lineHeight};`);
    lines.push(`  --text-${name}--letter-spacing: ${s.tracking}em;`);
  }
  lines.push("}");
  return lines.join("\n");
}

/** A Style Dictionary source, for institutions with an existing token pipeline. */
export function styleDictionaryTokens(state: BrandState): string {
  return JSON.stringify(
    {
      color: Object.fromEntries(
        state.palette.map((c) => [
          slug(c.name),
          {
            base: { value: c.hex, comment: c.usage },
            ...Object.fromEntries(
              ramp(c.hex).map((s) => [String(s.step), { value: s.hex }]),
            ),
          },
        ]),
      ),
      size: {
        font: Object.fromEntries(
          buildScale(state.typeBase, state.typeRatio, DEFAULT_STEPS).map((s) => [
            s.step >= 0 ? `up-${s.step}` : `down-${Math.abs(s.step)}`,
            { value: `${s.rem}rem`, comment: ROLE_FOR_STEP[s.step] },
          ]),
        ),
      },
    },
    null,
    2,
  );
}
